"""Add user_experience and user_education columns to User model

Revision ID: 0eeab210b755
Revises: 244651edd0d5
Create Date: 2024-12-05 21:43:29.985765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eeab210b755'
down_revision = '244651edd0d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
