"""Add user_experience and user_education columns to User model

Revision ID: 244651edd0d5
Revises: 76350a5b7b2f
Create Date: 2024-12-05 21:40:28.320210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '244651edd0d5'
down_revision = '76350a5b7b2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_experience', sa.JSON(), nullable=True))
    op.add_column('user', sa.Column('user_education', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_education')
    op.drop_column('user', 'user_experience')
    # ### end Alembic commands ###
