"""Add last_seen column to User model

Revision ID: 76350a5b7b2f
Revises: f891c49b03e1
Create Date: 2024-12-05 20:09:12.363104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76350a5b7b2f'
down_revision = 'f891c49b03e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('social_links', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'social_links')
    op.drop_column('user', 'last_seen')
    # ### end Alembic commands ###
