"""Add likes column to Project

Revision ID: c5680fbe1aef
Revises: 0eeab210b755
Create Date: 2025-01-13 11:29:56.887535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5680fbe1aef'
down_revision = '0eeab210b755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('likes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'likes')
    # ### end Alembic commands ###
